### ISSUE TITLE
The new click sound hurts my ears.

### ISSUE THREAD

**Issue by JasonTable** [minetest-mods/i3#91]
The new high-pitched chirp-like sound in the inventory menu is painful for users with sensory issues such as myself.

At first I honestly thought it was a bug and my sound file was corrupted because the sound reminds me of the sound a corrupted mp3 would make.

I think it needs to be replaced with a better sound. I could make my own CC0 sound and contribute it if needed.

**Comment by kilbith** [comment]
isn't it a bit like an exaggeration? Let's see if there are other complaints.

**Comment by Montandalar** [comment]
I couldn't agree more with OP. I was seriously considering giving i3 a decent go, but then I clicked through a few pages and it triggered my tinnitus quite badly despite being on the same volume settings as I would have when using Unified Inventory.

JP is either deaf to the frequency due to age/exposure, didn't notice it working in his environment or with his audio setup, or some other explanation.

And this is a real accessibility issue, not something to be disregarded. The page flip sound of unified inventory works fine. This one causes a nasty response in sensitive people.

**Comment by kilbith** [comment]
https://github.com/minetest-mods/i3/commit/e2fafbc876b35d79f82d727e4d27ab55a4399e06

Any better?
